name: React Application deploy 
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    
    - name: Install dependencies
      run: npm install 

    - name: CI
      run: npm ci
    - name: Build
      run: CI=false npm run build
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
          name: nmsweb
          path: ./build
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: nmsweb
      - name: Deploy to Azure
        uses: bacongobbler/azure-blob-storage-upload@main
        with: 
         source_dir: .       
         container_name: $web
         connection_string: ${{ secrets.DEPLOY_SAS_URL }}
        # WARNING: this will overwrite existing blobs in your blob storage
         overwrite: 'true'
